# Generated by Django 4.2 on 2023-04-18 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='content',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='subject',
            new_name='title',
        ),
    ]
