# Generated by Django 4.2 on 2023-04-18 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_content_answer_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='question',
            name='create_date',
        ),
    ]
